#! /usr/bin/env python2.7

import sys
import argparse

import config
import bikes

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('--db', metavar="URL", default=config.db_url,
                        help="Use this database instead of the default one.")
    parser.add_argument('--import', metavar='FILE', dest='import_', nargs='+',
                        help='Import these files into the database.')

    args = parser.parse_args()

    app = bikes.BorisBikesApp()

    if args.import_ is None:
        filename = app.save_bikes()
        if app.init_db(args.db, echo=args.verbose, require=False):
            app.import_xml(filename)
    else:
        app.init_db(args.db, echo=args.verbose)
        success = app.import_xml_multi(args.import_)
        if not success:
            sys.exit(1)

if __name__ == '__main__':
    main()
