#! /usr/bin/env python2.7

import argparse

import bikes

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='store_true')

    args = parser.parse_args()

    filename = bikes.save_bikes()

    engine = bikes.db_engine(echo=args.verbose)
    if engine is None:
        return

    tables = bikes.tables()
    tables.meta.create_all(engine)

    statsnaps = bikes.parse_xml(filename)
    bikes.insert_statsnaps(engine.connect(), tables, statsnaps)

if __name__ == '__main__':
    main()
