#! /usr/bin/env python2.7

import sys
import argparse

import bikes

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('--db', metavar="URL",
                        help="Use this database instead of the default one.")
    parser.add_argument('--import', metavar='FILE', dest='import_', nargs='+',
                        help='Import these files into the database.')

    args = parser.parse_args()

    if args.import_ is None:
        filename = bikes.save_bikes()
        bikes.import_xml(filename, args.verbose)
    else:
        success = bikes.import_xml_multi(args.import_, args.verbose)
        if not success:
            print >>sys.stderr, \
                "Failed to import. Have you set up config.db_uri?"
            sys.exit(1)

if __name__ == '__main__':
    main()
